### ISSUE TITLE
How to make Vertical icons?

### ISSUE THREAD

**Issue by AyanamiRei1** [sodasoba1/NSW-Custom-Game-Icons#1]
The images themselves are 256x256 but what the actual resolution of the images before making them 256x256?

Thanks.

**Comment by sodasoba1** [comment]
`422 X 256` if you checkout  GBAtemp https://gbatemp.net/threads/custom-game-icons-tutorial-and-sharing-hub-no-forwarders.574675/ for sys-tweak it will explain there.

I also have a template repository for making covers
https://github.com/sodasoba1/NSW-custom-icon-template.

Icons must be under 128kb (aim for 120kb for compatibility) and don't save interlaced/progressive

Save as base jpg
