### ISSUE TITLE
use ftpd-light

### ISSUE THREAD

**Issue by impeeza** [sodasoba1/NSW-Custom-Game-Icons#4]
Hi,  I do prefer to use ftpd-light because I don't have to run the server manually, is a demon on background, and has security, so my switch no get damaged or hacked when I use ldnmt.

It will be nice to add support for authentication on the FTP settings allowing to specify username and password for FTP connection.  thanks a lot for all your effort.

**Comment by sodasoba1** [comment]
I agree, unfortunately you need to pull an issue out with nx-gic dev

https://github.com/hotshotz79/NX-Game-Icon-Customizer
