### ISSUE TITLE
Crashes when adding sys-tweak

### ISSUE THREAD

**Issue by naldo29** [sodasoba1/NSW-Custom-Game-Icons#5]
every time i add systweak, it stays on the Nintendo switch logo and never goes into HOS.

**Comment by Maver1ckGaming** [comment]
You need the latest sys-tweak. You can grab it below.
https://www.mediafire.com/file/1g6c0l2cyf58eiy/exefs.nsp/file

**Comment by sodasoba1** [comment]
I'll try and add details about using sys-tweak and make them clearer but this has been mentioned in the wiki.
