### ISSUE TITLE
Using a vertical icon theme is blurry

### ISSUE THREAD

**Issue by Rakau** [sodasoba1/NSW-Custom-Game-Icons#9]
Looks like it's stretched through 256x256?

**Comment by sodasoba1** [comment]
It's a limitation of how we do vertical themes, nothing Ng can be done about it.

**Comment by Rakau** [comment]
> It's a limitation of how we do vertical themes, nothing Ng can be done about it.

Is this one of those OS limitations?

**Comment by sodasoba1** [comment]
> > It's a limitation of how we do vertical themes, nothing Ng can be done about it.
> 
> Is this one of those OS limitations?

Exactly
